name: Django CI

on:
  push:
    branches: test


jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Deploy to Heroku
      env: 
        HEROKU_API_KEY: ${{secrets.HEROKU_API_TOKEN}}
        HEROKU_APP_NAME: ${{secrets.HEROKU_API_NAME}}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        # git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git/
        git push heroku  main -f
      

